## Creates folders in working directory
dir.create(here("data"))
dir.create(here("data", "original"))
dir.create(here("data", "recoded"))
dir.create(here("documents"))
dir.create(here("output"))
dir.create(here("output", "figures"))
dir.create(here("output", "tables"))
dir.create(here("output", "LCA"))
dir.create(here("output", "LCA", "BCH"))
dir.create(here("output", "LCA", "model_selection"))
dir.create(here("output", "LCA", "sensitivity"))
dir.create(here("output", "LCA", "Severity"))
dir.create(here("output", "LCA", "Parents_sep"))
dir.create(here("output", "LCA", "count"))
dir.create(here("scripts"))